env:
  env_name: ContinuousInsertionRandomizedMarkerEnv-v1
  final_reward: 10
  marker_interval_range: [1.95, 2.15]
  marker_lose_tracking_probability: 0.01
  marker_pos_shift_range: [0.1, 0.1]
  marker_random_noise: 0.5
  marker_rotation_range: 0.1
  marker_translation_range: [1, 1]
  max_action: [2.0, 2.0, 4.0]
  max_steps: 8
  normalize: false
  params:
    allow_self_collision: false
    ccd_max_iters: 100
    ccd_slackness: 0.7
    ccd_tet_inversion_thres: 0.0
    ccd_thickness: 1e-06
    ee_classify_thres: 0.001
    ee_mollifier_thres: 0.001
    gripper_x_offset: [-1, 1]
    gripper_z_offset: [-10, -6]
    hole_friction: [0.0, 1.0]
    indentation_depth: [0.5, 1.25]
    line_search_max_iters: 10
    peg_friction: [4.0, 15.0]
    sim_d_hat: 0.0001
    sim_eps_d: 0
    sim_eps_v: 0.01
    sim_kappa: 100.0
    sim_kappa_affine: 100000.0
    sim_kappa_con: 10000000000.0
    sim_solver_cg_error_frequency: 10
    sim_solver_cg_error_tolerance: 0
    sim_solver_cg_max_iters: 50
    sim_solver_newton_max_iters: 5
    sim_time_step: 0.1
    tac_density_l: 1000.0
    tac_density_r: 1000.0
    tac_elastic_modulus_l: [300000.0, 300000.0]
    tac_elastic_modulus_r: [300000.0, 300000.0]
    tac_friction: [50.0, 125.0]
    tac_poisson_ratio_l: [0.3, 0.3]
    tac_poisson_ratio_r: [0.3, 0.3]
    tac_sensor_meta_file: gelsight_mini_e430/meta_file
  peg_hole_path_file: configs/peg_insertion/3shape_1.5mm.txt
  peg_theta_max_offset: 10.0
  peg_x_max_offset: 5.0
  peg_y_max_offset: 5.0
  step_penalty: 1
  z_step_size: 0.125